apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen2-vl-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen2-vl
  template:
    metadata:
      labels:
        app: qwen2-vl
    spec:
      containers:
      - name: qwen2-vl-container
        image: briancaffey/qwen2-vl:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: HUGGING_FACE_HUB_TOKEN
      restartPolicy: Always
      volumes:
      - name: huggingface-cache
        persistentVolumeClaim:
          claimName: huggingface-pvc
