apiVersion: v1
kind: Service
metadata:
  name: qwen2-vl-service
  namespace: default
spec:
  selector:
    app: qwen2-vl
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort